name: tailor_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9

  # Authentication
  google_sign_in: ^6.2.1
  auth_buttons: ^3.0.2

  # UI Components
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.1.1

  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true