// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRagTSRZomClFZ4Z0XoSWEo_bmVEw3lk',
    appId: '1:353326856521:web:42c428f2e0e6ef0ce14298',
    messagingSenderId: '353326856521',
    projectId: 'tailor-f929b',
    authDomain: 'tailor-f929b.firebaseapp.com',
    storageBucket: 'tailor-f929b.firebasestorage.app',
    measurementId: 'G-V386MD5Z6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1p_-VttTGbaG5JvAc4rFrINFK1vJiMxc',
    appId: '1:353326856521:android:d436591b1c768161e14298',
    messagingSenderId: '353326856521',
    projectId: 'tailor-f929b',
    storageBucket: 'tailor-f929b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNBLRoG9nfFpPvnu8Kq1GXH5yEZhpkkHM',
    appId: '1:353326856521:ios:dc7c299fb1b384d4e14298',
    messagingSenderId: '353326856521',
    projectId: 'tailor-f929b',
    storageBucket: 'tailor-f929b.firebasestorage.app',
    iosBundleId: 'com.example.SewCraftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNBLRoG9nfFpPvnu8Kq1GXH5yEZhpkkHM',
    appId: '1:353326856521:ios:dc7c299fb1b384d4e14298',
    messagingSenderId: '353326856521',
    projectId: 'tailor-f929b',
    storageBucket: 'tailor-f929b.firebasestorage.app',
    iosBundleId: 'com.example.SewCraftApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsRagTSRZomClFZ4Z0XoSWEo_bmVEw3lk',
    appId: '1:353326856521:web:068fc6fc90a01315e14298',
    messagingSenderId: '353326856521',
    projectId: 'tailor-f929b',
    authDomain: 'tailor-f929b.firebaseapp.com',
    storageBucket: 'tailor-f929b.firebasestorage.app',
    measurementId: 'G-B2HN3DK1QW',
  );
}
